version: '3.7'

services:
  back:
    container_name: simple_diary_back
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    command: uvicorn main:app --reload --port 80 --host 0.0.0.0
    ports:
      - 8080:80
    restart: always


